name: Publish Packages

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - website/**
      - .github/workflows/docs.yml

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add NPM registry
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install
        run: npm ci

      - name: Publish Release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
